services:
  - type: web
    name: andrzej-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    env: python
    region: frankfurt
    plan: free
    branch: main
    repo: https://github.com/Lumon345/Telegram-Bot
